# Generated by Django 4.2.9 on 2026-05-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'App Settings',
            },
        ),
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('body_ar', models.TextField()),
                ('body_en', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('order_status', 'Order Status'), ('price_change', 'Price Change'), ('unavailable', 'Item Unavailable'), ('alternative', 'Alternative Suggested'), ('weight_diff', 'Weight Difference'), ('promotion', 'Promotion'), ('waitlist', 'Waitlist Restock'), ('general', 'General')], default='general', max_length=30)),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
