# Generated by Django 4.2.9 on 2026-05-23 11:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, help_text='ORD-YYYYMMDD-NNN, sequential per day', max_length=30, unique=True)),
                ('order_id', models.CharField(blank=True, db_index=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('accepted', 'Accepted'), ('preparing', 'Preparing'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=30)),
                ('delivery_address', models.TextField()),
                ('building_number', models.CharField(max_length=20)),
                ('floor_number', models.CharField(max_length=10)),
                ('apartment_number', models.CharField(max_length=10)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('delivery_latitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('delivery_longitude', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('delivery_name', models.CharField(max_length=150)),
                ('delivery_phone', models.CharField(max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=15, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('points_used', models.PositiveIntegerField(default=0)),
                ('points_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('points_value_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash on Delivery'), ('online', 'Online (Card/Visa)'), ('pos', 'POS on Delivery'), ('wallet', 'Wallet'), ('points', 'Loyalty Points'), ('mixed', 'Mixed')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('partial_refund', 'Partial Refund')], default='pending', max_length=20)),
                ('paymob_order_id', models.CharField(blank=True, max_length=200)),
                ('customer_notes', models.TextField(blank=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('closed_by', models.CharField(blank=True, choices=[('customer', 'Customer'), ('driver', 'Driver Auto-close'), ('admin', 'Admin')], max_length=20)),
                ('driver_proof_image', models.ImageField(blank=True, null=True, upload_to='delivery_proofs/')),
                ('delivery_photo_url', models.URLField(blank=True, max_length=500)),
                ('closed_by_driver_at', models.DateTimeField(blank=True, null=True)),
                ('promotion_code', models.CharField(blank=True, max_length=50)),
                ('promotion_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('preparing_at', models.DateTimeField(blank=True, null=True)),
                ('out_for_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('points_awarded', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('price_change', 'Price Change'), ('quantity_change', 'Quantity Change'), ('qty_change', 'Quantity Change'), ('substitute_suggested', 'Substitute Suggested'), ('substitute_approved', 'Substitute Approved'), ('substitute_rejected', 'Substitute Rejected'), ('substitute', 'Product Substituted'), ('weight_diff_sent', 'Weight Diff Sent'), ('weight_diff_approved', 'Weight Diff Approved'), ('weight_diff_rejected', 'Weight Diff Rejected'), ('item_added', 'Item Added'), ('item_removed', 'Item Removed'), ('barcode_scanned', 'Barcode Scanned'), ('photo_taken', 'Photo Taken'), ('data_shared', 'Customer Data Shared'), ('status_changed', 'Status Changed'), ('call_attempt', 'Call Attempt')], max_length=30)),
                ('adjustment_type', models.CharField(blank=True, max_length=30)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('customer_approval_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20, null=True)),
                ('customer_approval_at', models.DateTimeField(blank=True, null=True)),
                ('customer_approved', models.BooleanField(blank=True, null=True)),
                ('new_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approval_deadline', models.DateTimeField(blank=True, null=True)),
                ('timeout_task_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_ar', models.CharField(max_length=200)),
                ('product_name_en', models.CharField(max_length=200)),
                ('product_barcode', models.CharField(blank=True, max_length=50)),
                ('unit_type', models.CharField(blank=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=8)),
                ('requested_qty', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('actual_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('delivered_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('line_total_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked', 'Picked'), ('collected', 'Collected'), ('unavailable', 'Unavailable'), ('substituted', 'Substituted'), ('weight_adjusted', 'Weight Adjusted'), ('price_adjusted', 'Price Adjusted'), ('added', 'Added by Agent'), ('removed', 'Removed'), ('rejected', 'Rejected by Customer')], default='pending', max_length=20)),
                ('added_by_agent', models.BooleanField(default=False)),
                ('added_by_driver', models.BooleanField(default=False)),
                ('customer_approved', models.BooleanField(blank=True, null=True)),
                ('agent_notes', models.TextField(blank=True)),
                ('driver_notes', models.TextField(blank=True)),
                ('weight_ordered', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('weight_actual', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('weight_difference_approved', models.BooleanField(blank=True, null=True)),
                ('weight_variance', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('weight_variance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('delivery_rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rating_photos/')),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('sentiment', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartTimerAutoClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_marked_delivered_at', models.DateTimeField(auto_now_add=True)),
                ('auto_close_scheduled_at', models.DateTimeField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timer', to='orders.order')),
            ],
            options={
                'ordering': ['-driver_marked_delivered_at'],
            },
        ),
    ]
