# Generated by Django 4.2.9 on 2026-05-23 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promotions', '0001_initial'),
        ('branches', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='stores.store'),
        ),
        migrations.AddField(
            model_name='deliveryfee',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_fees', to='branches.branch'),
        ),
        migrations.AddField(
            model_name='deliveryfee',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_fees', to='stores.store'),
        ),
        migrations.AddIndex(
            model_name='promotionusage',
            index=models.Index(fields=['promotion', 'user'], name='promotions__promoti_ac6da2_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['store', 'is_active'], name='promotions__store_i_946772_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['code'], name='promotions__code_e9f529_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_at', 'end_at'], name='promotions__start_a_d36ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryfee',
            index=models.Index(fields=['store', 'branch', 'is_active'], name='promotions__store_i_5f7dee_idx'),
        ),
    ]
