# Generated by Django 4.2.9 on 2026-05-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('phone', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_radius_km', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=15, max_digits=8)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text='{"open":"09:00","close":"23:00","days":[1,2,3,4,5,6,7]}')),
                ('is_coastal', models.BooleanField(default=False)),
                ('coastal_start_date', models.DateField(blank=True, null=True)),
                ('coastal_end_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'ordering': ['store', 'sort_order', 'name'],
            },
        ),
    ]
