# Generated by Django 4.2.9 on 2026-07-28 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('geometry', models.JSONField(help_text='GeoJSON Polygon or MultiPolygon, [lng, lat]')),
                ('bbox', models.JSONField(blank=True, help_text='[min_lng, min_lat, max_lng, max_lat] — derived, do not edit', null=True)),
                ('source', models.CharField(choices=[('drawn', 'Drawn on the map'), ('circle', 'Converted from delivery radius'), ('imported', 'Imported boundary')], default='drawn', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='branches.branch')),
            ],
            options={
                'ordering': ['branch', 'name_ar'],
                'indexes': [models.Index(fields=['branch', 'is_active'], name='branches_de_branch__4ab16e_idx')],
            },
        ),
    ]
