# Generated by Django 4.2.9 on 2026-05-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('supermarket', 'Supermarket'), ('pharmacy', 'Pharmacy'), ('electronics', 'Electronics'), ('bakery', 'Bakery'), ('restaurant', 'Restaurant'), ('other', 'Other')], max_length=20)),
                ('description_ar', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('cover_image_url', models.URLField(blank=True, max_length=500)),
                ('primary_color_hex', models.CharField(default='#FF6B35', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name_en'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='stores_stor_is_acti_5ed80d_idx')],
            },
        ),
    ]
